server:
  port: 8192
spring:
  application:
    name: spring-cloud-iproduct-test
uaa.queryOrganizationById.url: http://spring-cloud-uaa/api/v1/organizations/
eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}
    health-check-url: http://${spring.cloud.client.ipAddress}:${server.port}/health
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://192.168.18.205:1111/eureka/,http://192.168.18.205:1112/eureka/,http://192.168.18.205:1113/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 2000